import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PilatDemi from "next/font/local";

import "./globals.css";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const pilatDemi = PilatDemi({
  src: "../public/fonts/PilatExtended-DemiBold.woff2",
  display: "swap",
  variable: "--font-pilat-demi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${pilatDemi.variable}`}>
        {children}
      </body>
    </html>
  );
}
